name: Build teams.json

on:
  workflow_dispatch: # allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate teams.json
        run: |
          node scripts/generate-teams-json.mjs

      - name: Commit and push teams.json
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add teams.json
          git commit -m "chore: build teams.json" || echo "No changes to commit"
          git push
