name: Build teams.json

on:
  workflow_dispatch:
  push:
    paths:
      - "logos1/vendor/**"
      - "data/league-map.json"
      - "data/colors.json"
      - "data/stadiums.json"
      - "scripts/generate-teams.mjs"
      - ".github/workflows/build-teams.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install palette deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i node-vibrant@3 sharp@0.33.4

      - name: Generate teams.json
        run: node scripts/generate-teams.mjs

      - name: Commit and push teams.json
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add teams.json
            git commit -m "chore: build teams.json"
            git push
          else
            echo "No changes to commit."
          fi
